# Generated by Django 4.1 on 2022-09-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='current_value',
            new_name='starting_value',
        ),
    ]
