# Generated by Django 4.1 on 2022-09-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_current_value_listing_starting_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='value',
        ),
    ]
