# Generated by Django 4.1 on 2022-09-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_auction_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='auction_active',
            field=models.BooleanField(default=True),
        ),
    ]
