# Generated by Django 5.0.4 on 2024-04-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='end_time',
        ),
    ]
